import type { Metadata } from "next";
import "../styles/globals.css";

import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import Error from "./error";
import ClientWrapper from "@/components/client/layout/ClientWrapper";

export const metadata: Metadata = {
  title: "Itoll E-Commerce",
  description: "Generated by Itoll Task",
  applicationName: "Itoll E-Commerce",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Itoll E-Commerce",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="apple-touch-icon" href="/icons/icon-192x192.png" />
      </head>
      <body>
        <ClientWrapper>
          <ErrorBoundary errorComponent={Error}>{children}</ErrorBoundary>
        </ClientWrapper>
      </body>
    </html>
  );
}
