import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/libs/redux/StoreProvider";
import ThemeWrapper from "@/theme/ThemeWrapper";
import { AppBar, Button, Container, Toolbar, Typography } from "@mui/material";
import Image from "next/image";
import { img } from "@/constants/images";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import Error from "./error";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Itoll e-commerce",
  description: "Generated by Itoll Task",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeWrapper>
          <StoreProvider>
            <AppBar position="fixed" sx={{ backgroundColor: "text.primary" }}>
              <Toolbar>
                <Typography variant="h6" sx={{ flexGrow: 1 }}>
                  Itoll E-Commerce
                </Typography>
                <Button variant="text">
                  <Image
                    src={img.logo}
                    alt="logo"
                    width={50}
                    height={50}
                    priority={false}
                  />
                </Button>
              </Toolbar>
            </AppBar>
            <Container maxWidth="xl" sx={{ p: 2, pt: 5 }}>
              <ErrorBoundary errorComponent={Error}>{children}</ErrorBoundary>
            </Container>
          </StoreProvider>
        </ThemeWrapper>
      </body>
    </html>
  );
}
